version: '3.8'
services:
  ashuappfinal:
    image: jjcustomer:v1 
    build: . # location of dockerfile 
    container_name: jjwebappcust1
    ports:
    - "1155:80"
    restart: always 
    environment: 
      deploy: "app1"
